# This is a basic workflow to help you get started with Actions
name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    secrets: inherit
EOF
cat .github/workflows/build.yml
